### ISSUE TITLE
evaluation code is extremely slow

### ISSUE THREAD

**Issue by HumanZhong** [google-research-datasets/hiertext#12]
Hi, 

I'm using the provided eval.py for evaluation. However, the time cost is quite large. Running just line-level evaluation may cost 30+ minutes. 

Since I'm not familiar with Apache Beam, I'm not sure this is normal or not. I've tried increasing the `num_workers` param to 10 but it does not help.

Can you give me some advice on how to accelerate the evaluation process?

btw, these three parts cost most of the time: 1. pipeline creating 2. 'Read' 3. 'Eval'

![image](https://user-images.githubusercontent.com/31882926/216544110-f782eec3-f6f7-4419-89c1-0eeb8970135c.png)

**Comment by longshangbang** [comment]
It could take a long time indeed, because the dataset is very dense and lines are rendered as high-res masks.

As noted in the script, you can alternatively use the mask stride flag in the script to downsample the mask to save time. This will greatly reduce the time needed, but slightly sacrifice the accuracy of the evaluation metrics. You can try different mask strides yourselves to understand how metrics are affected by this flag, and select the best one to accelerate your development.
